// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenRAG.Api.Data;

#nullable disable

namespace OpenRAG.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260330035758_AddDocumentLegalMetadata")]
    partial class AddDocumentLegalMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("OpenRAG.Api.Models.Entities.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Key = "Llm:BaseUrl",
                            Value = ""
                        },
                        new
                        {
                            Key = "Llm:ApiKey",
                            Value = ""
                        },
                        new
                        {
                            Key = "Llm:Model",
                            Value = "gpt-4o-mini"
                        },
                        new
                        {
                            Key = "Llm:Temperature",
                            Value = "0.2"
                        },
                        new
                        {
                            Key = "Llm:MaxTokens",
                            Value = "2048"
                        },
                        new
                        {
                            Key = "Llm:SystemPrompt",
                            Value = ""
                        });
                });

            modelBuilder.Entity("OpenRAG.Api.Models.Entities.ChatMessageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("OpenRAG.Api.Models.Entities.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Collection")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChatSessions");
                });

            modelBuilder.Entity("OpenRAG.Api.Models.Entities.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoDetectHeadings")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChunkOverlap")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChunkSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadingScript")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SectionTokenThreshold")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Collections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutoDetectHeadings = true,
                            ChunkOverlap = 50,
                            ChunkSize = 400,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Default collection",
                            Name = "documents",
                            SectionTokenThreshold = 800
                        });
                });

            modelBuilder.Entity("OpenRAG.Api.Models.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentTypeDisplay")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("IndexedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("IssuedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssuingAuthority")
                        .HasColumnType("TEXT");

                    b.Property<string>("LegalBasisJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarkdownContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferencedDocsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignedLocation")
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<string>("TerminologyJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("Status");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("OpenRAG.Api.Models.Entities.ChatMessageEntity", b =>
                {
                    b.HasOne("OpenRAG.Api.Models.Entities.ChatSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("OpenRAG.Api.Models.Entities.Document", b =>
                {
                    b.HasOne("OpenRAG.Api.Models.Entities.Collection", "Collection")
                        .WithMany("Documents")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("OpenRAG.Api.Models.Entities.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("OpenRAG.Api.Models.Entities.Collection", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
