// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenRAG.Api.Data;

#nullable disable

namespace OpenRAG.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("OpenRAG.Api.Models.Entities.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Key = "Llm:BaseUrl",
                            Value = ""
                        },
                        new
                        {
                            Key = "Llm:ApiKey",
                            Value = ""
                        },
                        new
                        {
                            Key = "Llm:Model",
                            Value = "gpt-4o-mini"
                        },
                        new
                        {
                            Key = "Llm:Temperature",
                            Value = "0.2"
                        },
                        new
                        {
                            Key = "Llm:MaxTokens",
                            Value = "2048"
                        },
                        new
                        {
                            Key = "Llm:SystemPrompt",
                            Value = ""
                        });
                });

            modelBuilder.Entity("OpenRAG.Api.Models.Entities.ChatMessageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("OpenRAG.Api.Models.Entities.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Collection")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChatSessions");
                });

            modelBuilder.Entity("OpenRAG.Api.Models.Entities.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoDetectHeadings")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChunkOverlap")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChunkSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadingScript")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SectionTokenThreshold")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Collections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutoDetectHeadings = true,
                            ChunkOverlap = 50,
                            ChunkSize = 400,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Default collection",
                            Name = "documents",
                            SectionTokenThreshold = 800
                        });
                });

            modelBuilder.Entity("OpenRAG.Api.Models.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentTypeDisplay")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DomainId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("IndexedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("IssuedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssuingAuthority")
                        .HasColumnType("TEXT");

                    b.Property<string>("LegalBasisJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarkdownContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferencedDocsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignedLocation")
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SuggestedDomainsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<string>("TerminologyJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("ContentHash");

                    b.HasIndex("DomainId");

                    b.HasIndex("Status");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("OpenRAG.Api.Models.Entities.Domain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Domains");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ngân hàng - Tín dụng",
                            Slug = "ngan-hang-tin-dung"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tài chính",
                            Slug = "tai-chinh"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Doanh nghiệp",
                            Slug = "doanh-nghiep"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Đầu tư",
                            Slug = "dau-tu"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Công nghệ thông tin",
                            Slug = "cong-nghe-thong-tin"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Quản lý ngoại hối",
                            ParentId = 1,
                            Slug = "quan-ly-ngoai-hoi"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Thanh toán",
                            ParentId = 1,
                            Slug = "thanh-toan"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Mạng lưới hoạt động",
                            ParentId = 1,
                            Slug = "mang-luoi-hoat-dong"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Xếp hạng - Giám sát",
                            ParentId = 1,
                            Slug = "xep-hang-giam-sat"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Phân loại nợ - Trích lập dự phòng",
                            ParentId = 1,
                            Slug = "phan-loai-no"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Cho vay",
                            ParentId = 1,
                            Slug = "cho-vay"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Cấp phép",
                            ParentId = 1,
                            Slug = "cap-phep"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Thuế - Phí - Lệ phí",
                            ParentId = 2,
                            Slug = "thue-phi-le-phi"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Kế toán - Kiểm toán",
                            ParentId = 2,
                            Slug = "ke-toan-kiem-toan"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Ngân sách nhà nước",
                            ParentId = 2,
                            Slug = "ngan-sach-nha-nuoc"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Thành lập - Đăng ký",
                            ParentId = 3,
                            Slug = "thanh-lap-dang-ky"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Quản trị - Điều hành",
                            ParentId = 3,
                            Slug = "quan-tri-dieu-hanh"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Đầu tư nước ngoài",
                            ParentId = 4,
                            Slug = "dau-tu-nuoc-ngoai"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Chứng khoán",
                            ParentId = 4,
                            Slug = "chung-khoan"
                        },
                        new
                        {
                            Id = 50,
                            Name = "An toàn thông tin",
                            ParentId = 5,
                            Slug = "an-toan-thong-tin"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Giao dịch điện tử",
                            ParentId = 5,
                            Slug = "giao-dich-dien-tu"
                        });
                });

            modelBuilder.Entity("OpenRAG.Api.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OpenRAG.Api.Models.Entities.ChatMessageEntity", b =>
                {
                    b.HasOne("OpenRAG.Api.Models.Entities.ChatSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("OpenRAG.Api.Models.Entities.Document", b =>
                {
                    b.HasOne("OpenRAG.Api.Models.Entities.Collection", "Collection")
                        .WithMany("Documents")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenRAG.Api.Models.Entities.Domain", "Domain")
                        .WithMany("Documents")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Collection");

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("OpenRAG.Api.Models.Entities.Domain", b =>
                {
                    b.HasOne("OpenRAG.Api.Models.Entities.Domain", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("OpenRAG.Api.Models.Entities.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("OpenRAG.Api.Models.Entities.Collection", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("OpenRAG.Api.Models.Entities.Domain", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
